//HintName: DiscriminatedUnionGenerator.g.cs
// <auto-generated/>
#nullable enable

partial record EmptyUnion
{
    [global::System.CodeDom.Compiler.GeneratedCode("Funcky.DiscriminatedUnion.SourceGeneration", "1.1.0.0")]
    public abstract TResult Match<TResult>();
    
    [global::System.CodeDom.Compiler.GeneratedCode("Funcky.DiscriminatedUnion.SourceGeneration", "1.1.0.0")]
    public abstract void Switch();
}
