//HintName: DiscriminatedUnionGenerator.g.cs
// <auto-generated/>
#nullable enable

[global::System.Text.Json.Serialization.JsonDerivedType(typeof(Ok), "Ok")]
[global::System.Text.Json.Serialization.JsonDerivedType(typeof(Error), "Error")]
partial record Result
{
    [global::System.CodeDom.Compiler.GeneratedCode("Funcky.DiscriminatedUnion.SourceGeneration", "1.0.0.0")]
    public abstract TResult Match<TResult>(global::System.Func<Ok, TResult> ok, global::System.Func<Error, TResult> error);
    
    [global::System.CodeDom.Compiler.GeneratedCode("Funcky.DiscriminatedUnion.SourceGeneration", "1.0.0.0")]
    public abstract void Switch(global::System.Action<Ok> ok, global::System.Action<Error> error);
    
    partial record Ok
    {
        [global::System.CodeDom.Compiler.GeneratedCode("Funcky.DiscriminatedUnion.SourceGeneration", "1.0.0.0")]
        public override TResult Match<TResult>(global::System.Func<Ok, TResult> ok, global::System.Func<Error, TResult> error) => ok(this);
        
        [global::System.CodeDom.Compiler.GeneratedCode("Funcky.DiscriminatedUnion.SourceGeneration", "1.0.0.0")]
        public override void Switch(global::System.Action<Ok> ok, global::System.Action<Error> error) => ok(this);
    }
    
    partial record Error
    {
        [global::System.CodeDom.Compiler.GeneratedCode("Funcky.DiscriminatedUnion.SourceGeneration", "1.0.0.0")]
        public override TResult Match<TResult>(global::System.Func<Ok, TResult> ok, global::System.Func<Error, TResult> error) => error(this);
        
        [global::System.CodeDom.Compiler.GeneratedCode("Funcky.DiscriminatedUnion.SourceGeneration", "1.0.0.0")]
        public override void Switch(global::System.Action<Ok> ok, global::System.Action<Error> error) => error(this);
    }
}
